### ISSUE TITLE
Extensions option breaks if local path contains a dot anywhere

### ISSUE THREAD

**Issue by razor-x** [koajs/send#79]
The regex in [this line](https://github.com/koajs/send/blob/44090017d7f95bf90d1673f5e29c28fea6cf90e9/index.js#L84) will match paths with a dot anywhere. In particular if I'm developing in the local folder `/home/razorx/web/example.com` and try to use the `extensions` option to serve `/foo` then `path = /home/razorx/web/example.com/foo` and will match the regex thus skipping the if block.

```
 if (extensions && !/\..*$/.exec(path)) {
```

**Comment by Necromos** [comment]
Isn't it fixed with https://github.com/koajs/send/pull/92 ?

**Comment by coderhaoxin** [comment]
yes :)

**Comment by AdenFlorian** [comment]
I don't think this regex works on windows machines, since the directory separators are backslashes `\`.

I believe the tests are failing on my windows machine, because of this.

We can probably fix it by using basename:
```js
!/\./.exec(basename(path))
```

**Comment by maxweisel** [comment]
@AdenFlorian I believe your fix reintroduced the bug if the basename contains a dot anywhere. I'm currently running into this issue. I tried switching to @Necromos's regex pattern, but it still fails.

To be honest, I don't fully understand why this regex exists in the first place. Is it to prevent searching for ".html.html" ?

Can we re-open this bug?

Max
